página routing.md traduzida para ptbr
vuejs-br/docs-next pull request #139
Opened 2020-10-01 20:31 UTC by forgondolin

Tradução da página `/src/guide/routing.md`

https://github.com/vuejs-br/docs-next/issues/128

2020-10-01 22:22 UTC, arthurbergmz requested changes
Olá, @forgondolin! Tudo certo?

Primeiramente, agradeço por estar nos ajudando com a tradução! (aliás, ótima tradução!)
Apenas deixei alguns pontos de revisão, tudo bem? Tentamos deixar o mais próximo possível da tradução que já fora realizada e revisada da V2, mas, obviamente, melhorando no que pudermos.

Referência da V2:
https://br.vuejs.org/v2/guide/routing.html

Valeu!

2020-10-01 22:22 UTC, arthurbergmz commented on src/guide/routing.md
> +## Roteador oficial (Official Router)
Não é necessário colocar "(Official Router)", neste caso. Isto se deve por não ser um termo que não existe em nosso vocabulário.

2020-10-01 22:22 UTC, arthurbergmz commented on src/guide/routing.md
> +Para a maioria das aplicações de página única (SPA), é recomendado utilizar a [biblioteca vue-router](https://github.com/vuejs/vue-router) oficial. Para mais detalhes, veja a [documentação](https://r
Poderia trocar "(SPA)" por `_(Single Page Applications)_`, por gentileza? O original não utiliza a sigla ;)

Também sugiro trocar `vue-router` por `_vue-router_`, já que este não é um pedaço de código, mas o nome de um pacote.

2020-10-01 22:22 UTC, arthurbergmz commented on src/guide/routing.md
> +Se você só precisa de um roteamento simples e não tem interesse de utilizar uma biblioteca robusta de roteamento, você pode o fazer dinamicamente, renderizando um componente no nível da página (page-
Por gentileza, corrigir o "de" em _"e não tem interesse de utilizar"_ por "em", já que expressamos interesse _em_ algo.
Portanto: "e não _possui_ interesse em utilizar"

Também utilizamos, na documentação, os termos originais - quando se fazem necessário - com itálico. Portanto:

```
renderizando um componente no nível da página (page-level component)
```

se torna:

```
renderizando um componente no nível da página _(page-level component)_
```

Também sugiro a atualização de "desse jeito" por "deste modo".

2020-10-01 22:22 UTC, arthurbergmz commented on src/guide/routing.md
> +Se você preferir utilizar um roteador de terceiros (3rd-party router), como por exemplo [Page.js](https://github.com/visionmedia/page.js) ou [Director](https://github.com/flatiron/director), a integr
Trocar, por gentileza:

```
(3rd-party router)
```

por

```
_(3rd-party router)_
```

2020-10-01 23:59 UTC, forgondolin commented on src/guide/routing.md
> +## Roteador oficial (Official Router)
Beleza, fiquei na dúvida quanto a isso também.

2020-10-02 00:02 UTC, forgondolin commented on src/guide/routing.md
> +Se você preferir utilizar um roteador de terceiros (3rd-party router), como por exemplo [Page.js](https://github.com/visionmedia/page.js) ou [Director](https://github.com/flatiron/director), a integr
feito

2020-10-02 00:02 UTC, forgondolin commented on src/guide/routing.md
> +Para a maioria das aplicações de página única (SPA), é recomendado utilizar a [biblioteca vue-router](https://github.com/vuejs/vue-router) oficial. Para mais detalhes, veja a [documentação](https://r
feito

2020-10-02 00:04 UTC, forgondolin commented
@arthurbergmz 
Obrigado pela revisão. Estou bem impressionado com o profissionalismo nas normas para tradução e revisão.
Espero contribuir mais.

2020-10-02 19:30 UTC, GuiDevloper commented
Bem vindo, @forgondolin.
Volte às nossas _issues_ quando quiser.
Interessante teus artigos e cyberpunk é incrível mesmo :)

2020-10-02 22:03 UTC, forgondolin commented
hahaha valeu @GuiDevloper , preciso escrever com mais frequência

2020-10-03 22:19 UTC, merged