Update "guide/component-template-refs.md"
vuejs-br/docs-next pull request #27
Opened 2020-09-16 20:00 UTC by dumedeiros

2020-09-17 01:33 UTC, GuiDevloper commented
Desculpa o desfalque contigo @dumedeiros, passei a tarde em experimentos do nosso futuro bot.
Seguinte, muita calma nessa hora, sofri bastante com esse bloqueio que PR faz também.
Para realizar outro trabalho, recomendo criar outra branch de master em seu repo e mandar PR dela.
Demorei pra sacar isso e Git é calma e experimentar bem em ambiente controlado e seu.

Outra coisa interessante é Stash, salva backup local do que está trabalhando para mudar de branch e afins.
Se precisar só marcar que apareço aí quando puder :)

2020-09-17 15:30 UTC, GuiDevloper requested changes
guide/component-template-refs.md OK

guide/instance.md
Mano @dumedeiros, realmente rolou uma cópia do Instance do v2?
Percebe-se que teve muita mudança na v3 e pedimos que a v2 seja usada apenas como leve referência.

PS: Como exemplo, esse é um caso que seria interessante trabalho dividido em branchs, pois fica impossibilitado mergear o template-refs.md

2020-09-17 16:56 UTC, dumedeiros commented
> guide/component-template-refs.md OK

2020-09-17 16:59 UTC, dumedeiros commented
> Mano @dumedeiros, realmente rolou uma cópia do Instance do v2?
> Percebe-se que teve muita mudança na v3 e pedimos que a v2 seja usada apenas como leve referência.


Mano @GuiDevloper, eu estou seguindo este passo a passo, conforme #20:

- Contribuidor faz fork deste repositório aqui;
- Avisa na issue correspondente em qual arquivo está trabalhando;
- Pega o arquivo correspondente (quando existir) na **documentação v2 em inglês e tenta colar por cima do arquivo novo em inglês do seu fork realizado**. Se não houverem trechos equivalentes, simplesmente traduz o arquivo;
- Usando o git diff, se houverem seções (às vezes vários parágrafos inteiros) que não mudaram de uma versão para outra**, pode acessar a tradução da v2 e aproveitar os mesmos trechos.** Senão, simplesmente traduz cada trecho necessário;
- Acabou de traduzir o arquivo; faz pull request contendo as alterações (atenção: o core team exige que todos os pull requests que subirão para upstream sejam descritos em inglês);
- Se algo der errado, demorar muito para traduzir ou sentir que não vai mais conseguir ajudar, avise na issue aberta para outra pessoa prosseguir;
- Se tudo der certo, parabéns e parte para o próximo.

2020-09-17 17:18 UTC, ErickPetru commented
@dumedeiros desculpe me intrometer, já que este _review_ é do @GuiDevloper, mas só para deixar claro para ambos o que eu quis dizer com aquela recomendação: colar por cima o conteúdo do arquivo (em inglês) da V2 no lugar do arquivo da V3 e utilizar o _git diff_ para facilitar a verificação se houveram mudanças desde nossa última tradução, para reaproveitar arquivo de tradução da V2. Mas isso só vai funcionar se a data da última alteração do arquivo da V2 em português mais recente que a última alteração do arquivo da V2 em inglês, pois não chegamos a atualizar todas as traduções desde quando eles congelaram os trabalhos das equipes de tradução por causa dos trabalhos na V3.

2020-09-17 18:43 UTC, GuiDevloper commented
Opa @dumedeiros, isso é bem como eu disse, muita calma nessa hora pois aprender bem com essa experiência será muito bom lá na frente.
Não precisa fechar o PR, tendo em vista que já tem um bom trabalho aí.
O Erick apontou uma forma interessante de considerar os trabalhos antigos, as datas dos arquivos.

No geral o _diff_ certeiro seria se atentando ao formato (titulo e tags) e novos códigos (ex: new Vue -> Vue.createApp) do arquivo e desconsiderando o antigo caso houver divergência quase que total.

2020-09-18 13:58 UTC, lpj145 commented
@ErickPetru talvez fosse pedir muito, mas a forma que você explicou parece clara, só que em adicional, há novatos que podem nem entender os amplos funcionamentos que o git tem, então seria pedir muito você fazer um vídeo curto explicando na pratica isso ai ? pegaria um arquivo pequeno e faz o exemplo, acho que seria bem legal, porque serviria até para processo futuros e engaja mais a comunidade.

2020-09-18 17:05 UTC, GuiDevloper commented
Opa @dumedeiros, seguinte meu caro
Os comments aqui tem todo um caráter profissional especificamente para tirar dúvidas e resolver problemas
Para ter uma ideia, eu mantenho comunicação rotineira com o Erick sem usarmos de chats privados, o que traz maior produtividade até porque os outros podem trazer suas soluções e é comum privado ter foco em algo emergencial, por exemplo.

Vai com calma e se sentir sua disposição abalada só avisar de boa.
Qualquer dúvida pontual só mandar aí que chega email lá.

Abraço e força aí!

2020-09-18 17:23 UTC, ErickPetru commented
@lpj145 acrescentando ao que o @GuiDevloper bem pontuou, favor não misturar os comentários de pull requests com sugestões e assuntos mais genéricos ao projeto. Sua ideia pode ser muito relevante, mas aqui ela está postada no lugar errado e certamente se perderá em meio a outras demandas.

Por gentileza, crie uma issue expondo suas ideias e certamente outros também se sentirão melhores se puderem contribuir opinando nas discussões.

2020-09-18 18:41 UTC, dumedeiros commented
Tudo bem então, vou refazer a tradução, como devo proceder então?
a) reverter o commit;
b) pegar o texto original em inglês, colar no arquivo que eu já traduzi e fazer commit pra voltar ao original
c) alguma outra sugestão

2020-09-18 18:52 UTC, GuiDevloper commented
Pensei que o melhor seria finalizar o trabalho que fez, agora levando em conta as novas recomendações (foco em manter integridade/formato do arquivo original da v3), @dumedeiros.
Talvez o @ErickPetru possa acrescentar, pra mim o certo é encontrar a melhor forma de finalizar o que tem feito.

2020-09-18 19:49 UTC, ErickPetru commented
@dumedeiros pra ser sincero, não olhei a fundo teu PR já que era o @GuiDevloper que estava revisando. Mas não gosto da ideia de jogar trabalho fora, e nada impede de publicar mais push nesse PR mesmo. Só toma cuidado para não ter perdido nenhuma novidade da doc da v3 ao reaproveitar conteúdos da v2. Dá uma revisada nesse sentido e adiciona commit neste PR mesmo. Avisa aqui por comentário quando sentir que terminou de vez neste arquivo, aí a gente sinaliza pra revisão de novo.

2020-09-18 20:42 UTC, dumedeiros commented
Pessoal, estou com dúvida quanto aos links.
Analisando o que existe no arquivo em inglês da V3 com o que existe tanto na V2 em inglês quanto em português, achei estas diferenças:

V3
...API reference]**(../api/options-data.html)**
V2 EN
...API reference]**(../api/#Options-Data)**
V2 PtBR
...documentação da API]**(../api/#Opcoes-Dados)** //Com hash e em **português**

V3
...the component system]**(component-basics.html)**
V2 EN
...the component system](**components.html)**
V2 PtBR
...sistema de componentes](**components.html)**

V3
...API reference]**(../api/instance-properties.html)**
V2 EN
...API reference]**(../api/#Instance-Properties)**
V2 PtBR
...documentação da API](**../api/#Propriedades-de-Instancia)**

V3
...created](../api/options-lifecycle-hooks.html#created) //Com hash e em **português**
V2 EN
...created`]**(../api/#created)**
V2 PtBR

 ...created`]**(../api/#created)**  //Com hash e em **INGLÊS**

Devo seguir com os links em inglês e sem hash, já que os links da versão V3 estão sem hash?

E no caso em que o link em inglês possui hash, como no link abaixo,, ele deve ser traduzido como aconteceu na V2(conforme mostrado acima)? 
V3
...created]**(../api/options-lifecycle-hooks.html#created)**

2020-09-18 21:15 UTC, GuiDevloper commented
Bem sacado @dumedeiros, não sei se essa recomendação seguiu no novo guia de contribuição, mas simplificado:
Quando títulos são traduzidos, as hashs que os referenciam também seriam.
No caso do `#created` deve se referir à _hook_, que é uma função da API em si, sem tradução.

2020-09-18 21:27 UTC, dumedeiros commented
Pois é, faz sentido isso que você falou quanto aos hooks.
Agora, já na parte com os links com hash, fica meio confuso, porque, primeiramente, eu não sei quais nomes seriam, nem me sinto à vontade para traduzir livremente. Por exemplo, no link:

(../api/#Instance-Properties)
eu poderia traduzir tanto para "Propriedades-de-Instancia" //assim é atradução "oficial"
ou para "Propriedades-**da**-Instancia"

Já no caso do 
(../api/#Options-Data)
foi traduzido para 
(../api/#Opcoes-Dados)

mas eu poderia traduzir livremente para:
(../api/#Opcoes-**de**-Dados) ou
(../api/#Opcoes-**dos**-Dados)
sem saber que tradução utilizar.

2020-09-18 21:27 UTC, dumedeiros commented
Só tá faltando isso para eu marcar para review!

2020-09-18 21:43 UTC, GuiDevloper commented
Se bobear acho que o VuePress até faria isso sozinho baseado nos títulos, @dumedeiros.
No geral o mais válido é manter um padrão, ex: traduziu um título, como descrevê-lo de forma descritível e distinta?
Se o título ficou Opções de Dados, o hash já se mostrou aí

2020-09-18 21:51 UTC, dumedeiros commented
A questão é: como a tradução de outras pessoas que precisem referenciar o mesmo link, vai usar o mesmo padrão?
(ou eu estou deixando escapar algum entendimento?)

2020-09-18 22:13 UTC, GuiDevloper commented
É algo meio polêmico por natureza, @dumedeiros.
Na verdade o link traduzido para tal lugar apenas deve nascer quando aquele lugar for traduzido, assim o link é mantido até então.

Ex: [instance#instance-lifecycle-hooks](https://v3.vuejs.org/guide/instance.html#instance-lifecycle-hooks)
Se traduzido o tradutor deve buscar pelo link/hash por toda doc e traduzir para o link gerado pela tradução dele, me equivoquei em não frisar que o Press realmente gera tudo sozinho e após essa geração que devemos usar os links dos títulos

2020-09-21 19:41 UTC, GuiDevloper commented
Primeiramente, parabéns por ter sacado a criação de outra PR, @dumedeiros.

To cheio de trabalho, mas não sai da mente o que tenho de fazer aí :sweat_smile:
É um bom motivo pra eu trazer o bot open-source @ErickPetru, tenho várias ideias mas tempo curto, queria ver o tanto que o pessoal (imagina tu, ein) poderia ajudar :)

2020-09-22 01:58 UTC, dumedeiros commented
Mano, @GuiDevloper, quando você fala:
> Primeiramente, parabéns por ter sacado a criação de outra PR, @dumedeiros.

Você tá se referindo a que, especificamente?  Seria referente ao PR com a nova tradução da seção "guide/conditional.md" (#7) que eu fiz? rsrs

2020-09-22 02:31 UTC, GuiDevloper commented
Era sim, @dumedeiros.
Agora parece que rolou uma boa mexida lá, depois vamos pegar um tempo pra dar uma olhada em como tudo fica no merge.

2020-09-22 02:53 UTC, dumedeiros commented
De nada, @GuiDevloper.

Vocês também estão me dando várias dicas que estão me ajudando no processo.

2020-09-23 15:07 UTC, ErickPetru commented
Como as traduções dos arquivos foram reenviadas no #33, estou fechando este PR para que os 3 arquivos daquele PR possam ser revisados em um único local, evitando confusões e trabalho duplicado.

2020-09-23 15:07 UTC, closed without merging