Tradução do arquivo "guide/forms.md" #10
vuejs-br/docs-next pull request #31
Opened 2020-09-17 03:33 UTC by LucasFlaquer

## Proposed Solution
file translation #10 "guide/forms.md"  

## Additional Information
I've got doubts about translating the codepe's link so I left the way it was

2020-09-17 17:24 UTC, ErickPetru requested changes

2020-09-17 17:24 UTC, ErickPetru commented on src/guide/forms.md
>  `v-model` will ignore the initial `value`, `checked` or `selected` attributes found on any form elements. It will always treat the current active instance data as the source of truth. You should decl
As dicas e avisos também precisam ser traduzidos.

2020-09-17 17:24 UTC, ErickPetru commented on src/guide/forms.md
>  <p class="codepen" data-height="300" data-theme-id="39028" data-default-tab="result" data-user="Vue" data-slug-hash="eYNPEqj" data-editable="true" style="height: 300px; box-sizing: border-box; displa
Na doc V2 chegamos a fazer fork e traduzir muitos CodePens. Seria legal conferir se os exemplos ainda são os mesmos e aproveitar os links da V2.

2020-09-18 00:16 UTC, LucasFlaquer commented on src/guide/forms.md
>  <p class="codepen" data-height="300" data-theme-id="39028" data-default-tab="result" data-user="Vue" data-slug-hash="eYNPEqj" data-editable="true" style="height: 300px; box-sizing: border-box; displa
@ErickPetru procurei os pens em português mas não os encontrei. Poderia me ajudar?

2020-09-18 00:18 UTC, LucasFlaquer commented on src/guide/forms.md
>  `v-model` will ignore the initial `value`, `checked` or `selected` attributes found on any form elements. It will always treat the current active instance data as the source of truth. You should decl
Eu realizei mais um commit atualizando esta parte. Preciso abrir outro pull Request ou é possível pegar as alterações a partir deste?

2020-09-18 00:49 UTC, ErickPetru commented on src/guide/forms.md
>  `v-model` will ignore the initial `value`, `checked` or `selected` attributes found on any form elements. It will always treat the current active instance data as the source of truth. You should decl
Não precisa, os commits são incrementais dentro do mesmo pull request.

2020-09-18 00:50 UTC, ErickPetru commented on src/guide/forms.md
>  <p class="codepen" data-height="300" data-theme-id="39028" data-default-tab="result" data-user="Vue" data-slug-hash="eYNPEqj" data-editable="true" style="height: 300px; box-sizing: border-box; displa
Este é arquivo traduzido da V2: https://github.com/vuejs-br/br.vuejs.org/blob/master/src/v2/guide/forms.md. Você pode dar uma olhada nos exemplos e ver se mudaram ou não.

2020-09-18 21:24 UTC, LucasFlaquer commented on src/guide/forms.md
>  <p class="codepen" data-height="300" data-theme-id="39028" data-default-tab="result" data-user="Vue" data-slug-hash="eYNPEqj" data-editable="true" style="height: 300px; box-sizing: border-box; displa
Obrigado. Eu andei lendo outros prs e vi que você comentou de fazer um fork para o codepen do vuejs-br então estou criando no meu codepen para depois serem feitos os forks. Assim que eu terminar aviso para poder colocar o link vindo do codepen do vuejs-br

2020-09-18 22:54 UTC, LucasFlaquer commented on src/guide/forms.md
>  <p class="codepen" data-height="300" data-theme-id="39028" data-default-tab="result" data-user="Vue" data-slug-hash="eYNPEqj" data-editable="true" style="height: 300px; box-sizing: border-box; displa
Lista de links para serem forkados no repositorio do vuejs-brasil no codepen:

[Lidando com formulários: v-model simples](https://codepen.io/LucasFlaquer/pen/bGpmqxR)

[Lidando com formulários: textarea](https://codepen.io/LucasFlaquer/pen/VwaEpNv)

[Lidando com formulários: checkbox](https://codepen.io/LucasFlaquer/pen/YzqJZoq)

[Lidando com Formulários: múltiplos checkboxes](https://codepen.io/LucasFlaquer/pen/zYqmwGV)

[Lidando com formulários: radiobutton](https://codepen.io/LucasFlaquer/pen/ExKdmjq)

[Lidando com formulários: select](https://codepen.io/LucasFlaquer/pen/RwaeVgg)

[Lidando com Formulários: seleção de múltiplos itens (vinculando a um Array)](https://codepen.io/team/Vue/pen/gOpBXPz)

[Lidando com Formulários: select com opções dinâmicas](https://codepen.io/LucasFlaquer/pen/JjXmNrG)

2020-09-19 13:45 UTC, ErickPetru commented
Olá @LucasFlaquer, aqui está a coleção com os _pens_ adicionados à conta vuejs-br: https://codepen.io/collection/XPEEqp.
Por favor, atualize sua tradução com estes links.

Além disso, por favor, desfaça os commits relacionados a merge de upstream, apenas a equipe de revisão faz merge de upstream diretamente neste repositório, senão os conflitos de merge e possíveis sobrescritas ficam descontrolados.

Ou seja, você deve enviar neste pull request apenas o arquivo a que ele se propõe: "guide/forms.md".

2020-09-19 19:27 UTC, LucasFlaquer commented
olá @ErickPetru desculpe pelo problema com o git quis baixar as ultimas altualizações. Não sabia que iria afetar este PR. Já atualizei os links

2020-09-24 16:33 UTC, ErickPetru commented
Olá @LucasFlaquer, ainda tá com problema por causa do merge. Para evitar mais confusões com PR e commit, se preferir guardar seu arquivo traduzido por aí, fechar este PR e enviar um novo só com o arquivo traduzido, não tem problema.

2020-09-25 21:08 UTC, closed without merging