translated guide/forms
vuejs-br/docs-next pull request #42
Opened 2020-09-25 21:15 UTC by LucasFlaquer

Translation of the guide/forms with correct links of the pens translated from the original

2020-09-26 20:40 UTC, arthurbergmz requested changes
Oi, @LucasFlaquer! Tudo certo contigo?

Antes de tudo, ótima tradução, cara! Agradeço muito por estar nos ajudando na tradução da documentação do Vue!
Há apenas alguns pontos simples que sugiro algumas mudanças. Poderia dar uma olhada nelas, por gentileza?

Qualquer coisa, só perguntar.
Valeu!

2020-09-26 20:40 UTC, arthurbergmz commented on src/guide/forms.md
> +Você pode usar a diretiva `v-model` para criar interligações de dados de mão dupla (two-way data binding) em elementos input, textarea e select de formulários. Ele automaticamente escolhe a maneira c
É bacana deixar o original, em inglês, após a tradução de termos técnicos. Poderia apenas deixá-los, além de entre parênteses, em itálico também, por gentileza? Exemplo:

interligações de dados de mão dupla _(two-way data binding)_
```
interligações de dados de mão dupla _(two-way data binding)_
```

é essencialmente uma forma simplificada(syntax sugar)
```
é essencialmente uma forma simplificada _(syntax sugar)_
```

Particularmente, achei interessante a adaptação de _syntax sugar_ como "forma simplificada".

2020-09-26 20:40 UTC, arthurbergmz commented on src/guide/forms.md
> +      checkedNames: [],
Por gentileza, não alterar sintaxe do código original (sei que é chato pedir isso, sorry <3)

2020-09-26 20:40 UTC, arthurbergmz commented on src/guide/forms.md
> +  },
So as in here, pls <3

2020-09-26 20:40 UTC, arthurbergmz commented on src/guide/forms.md
> +      picked: '',
`,` é uma sintaxe opcional neste caso, então, por ser questão de gosto, é mais interessante deixar como o código original que o Vue apresenta: sem as vírgulas. Deste modo, apresentamos como o Vue enxerga boas práticas.

2020-09-26 20:40 UTC, arthurbergmz commented on src/guide/forms.md
> +  },
Aaaaand in here as well <3

2020-09-26 20:40 UTC, arthurbergmz commented on src/guide/forms.md
> +  <span>veja o <i>Pen</i> <a href="https://codepen.io/vuejs-br/pen/VwaExpO">
Se possível, apenas coloque a letra `V` em `veja` desses pedaços de código do CodePen como maiúscula.

2020-09-26 20:40 UTC, arthurbergmz commented on src/guide/forms.md
> +Se o valor inicial da expressão `v-model` não corresponder match nenhuma das optções, o element `<select>` será renderizado em um estado "não selecionado". No iOS, isso impedirá o usuário de selecion
Por gentileza, corrigir "não corresponder ~~match~~ nenhuma das op~~t~~ções, o element**o**" para `não corresponder a nenhuma das opções, o elemento`.

Adicionar vírgula, também, após o "portanto".

2020-09-26 20:40 UTC, arthurbergmz commented on src/guide/forms.md
> +Para _radio_, _checkbox_ e _select_, a interligação de valores do `v-model` são sempre strings estáticas (ou valores booleanos no caso do _checkbox_):
Adicionar efeito itálico em `strings`, por gentileza.

Sugestão de tradução: `valores __boolean__` ao invés de "valores booleanos".

2020-09-26 20:40 UTC, arthurbergmz commented on src/guide/forms.md
> +Mas às vezes podemos querer vincular o valor à uma propriedade dinâmica na atual instância ativa. Nós podemos utilizar `v-bind` para alcançar isso. Além disso, utilizando `v-bind` nos permite vincula
"valores que não são uma string (non-string values)"

por

"valores que não são uma _string_ _(non-string values)_"
```
_string_ _(non-string values)_`
```

2020-09-26 20:40 UTC, arthurbergmz commented on src/guide/forms.md
> +Os atributos `true-value` e `false-value` não afetam o atributo `value` dos _input's_, porque os browsers não incluem caixas de seleção não assinaladas nas submissões de formulários. Para garantir qu
Por gentileza, corrigir _input's_ por _inputs_.

O `'s` em `input's` atribui a posse do atributo `value` em `input`, não significando plural.

2020-09-26 20:40 UTC, arthurbergmz commented on src/guide/forms.md
> +Se você quiser que os espaços em branco do _input_ do usuário sejam automaticamente cortados, pode adicionar o modificador `trim` ao `v-model` do elemento:
"Se você quiser que os espaços em branco do _input_ do usuário sejam automaticamente cortados, pode adicionar o modificador `trim` ao `v-model` do elemento:"

Isso dá a entender que qualquer espaço em branco do _input_ serão automaticamente removidos. Uma função `trim()` remove apenas espaços _excedentes_.

Portanto, é importante explicitar este comportamento para não induzir usuários ao erro.
Sugestão de correção:

```
Se você quiser que os espaços em branco excedentes de um _input_ sejam automaticamente removidos, 
é possível adicionar o modificador `trim` ao `v-model` do elemento:
```

2020-09-26 20:40 UTC, arthurbergmz commented on src/guide/forms.md
> +os tipos de _input_ nativos do HTML nem sempre atendem as suas necessidades. Felizmente, os componentes Vue te permitem construir _inputs_ reutilizáveis com comportamento completamente costumizável.
O parágrafo está começando com letra minúscula ("os tipos"...). Por gentileza, poderia corrigir?

Se possível, também tornar `Para saber mais, leia sobre [inputs customizados]` em `Para saber mais, leia sobre [_inputs_ customizados]` (já que, em palavras ou termos estrangeiros, devemos colocar em itálico).

2020-09-28 16:50 UTC, LucasFlaquer commented
Olá @arthurbergmz, fico feliz que tenha gostado da minha tradução, realizei as correções (as virgulas tinham sido incluídas pelo editor acabei não reparando, me desculpe. Acredito ter realizado todas as correções. Qualquer coisa esto à disposição

2020-09-29 12:37 UTC, arthurbergmz approved these changes

2020-09-29 12:37 UTC, merged

2020-09-29 12:38 UTC, arthurbergmz commented
Valeu, @LucasFlaquer!!